allowBuilds:
  "@prisma/engines": true
  argon2: true
  cbor-extract: true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@arcevo/facet-cli@0.2.0 || 0.3.0'
  - '@arcevo/facet-auth@1.1.1'
  - '@arcevo/facet-components@1.3.0'
  - '@arcevo/facet-docs@1.3.0'
  - '@arcevo/facet-layout@1.2.0'
