-- Remove dead DELEGATION_GRANTED / DELEGATION_REVOKED enum values from AuditLogAction.
-- No code produces these values (delegation.route.ts is audit-free — verified by grep).
-- PostgreSQL cannot DROP VALUE from an enum, so we recreate the type without them.

CREATE TYPE "new_AuditLogAction" AS ENUM (
  'USER_LOGIN_SUCCESS',
  'USER_LOGIN_FAILED',
  'USER_REGISTERED',
  'USER_DELETED',
  'PROFILE_UPDATED',
  'PASSWORD_CHANGED',
  'USERNAME_SET',
  'MFA_ENABLED',
  'MFA_DISABLED',
  'MFA_RECOVERY_USED',
  'MFA_VERIFICATION_SUCCESS',
  'MFA_VERIFICATION_FAILED',
  'TOKEN_REVOKED',
  'SESSION_CREATED',
  'SESSION_REVOKED',
  'SESSION_REVOKED_ALL',
  'PASSKEY_REGISTERED',
  'PASSKEY_REMOVED',
  'PASSWORD_RESET_REQUESTED',
  'PASSWORD_RESET_COMPLETED',
  'EMAIL_VERIFIED',
  'EMAIL_VERIFICATION_SENT',
  'EXTERNAL_IDENTIFIER_LINKED',
  'EXTERNAL_IDENTIFIER_UNLINKED',
  'TENANT_CREATED',
  'TENANT_UPDATED',
  'SUBSCRIPTION_UPGRADED',
  'SUBSCRIPTION_CANCELLED',
  'WEBHOOK_DELIVERY_FAILED',
  'WEBHOOK_DELIVERED',
  'OAUTH_CLIENT_CREATED',
  'OAUTH_CLIENT_UPDATED',
  'OAUTH_CONSENT_GRANTED',
  'OAUTH_CONSENT_REVOKED',
  'TENANT_MEMBER_ADDED',
  'TENANT_MEMBER_REMOVED',
  'TENANT_POLICY_UPDATED',
  'SIGNING_KEY_CREATED',
  'SIGNING_KEY_REVOKED',
  'IDENTITY_CREATED',
  'IDENTITY_SUSPENDED',
  'IDENTITY_BANNED',
  'IDENTITY_DELETED',
  'IDP_CONNECTION_CREATED',
  'IDP_CONNECTION_UPDATED',
  'SESSION_ELEVATED',
  'EXTERNAL_IDENTIFIER_VERIFICATION_SENT',
  'EXTERNAL_IDENTIFIER_VERIFIED'
);

ALTER TABLE "AuditLog" ALTER COLUMN "actionId" TYPE "new_AuditLogAction" USING "actionId"::text::"new_AuditLogAction";
ALTER TABLE "WebhookEvent" ALTER COLUMN "eventType" TYPE "new_AuditLogAction" USING "eventType"::text::"new_AuditLogAction";

DROP TYPE "AuditLogAction";
ALTER TYPE "new_AuditLogAction" RENAME TO "AuditLogAction";
