ALTER TABLE "ExternalIdentifier" ADD COLUMN "verificationCode" TEXT;
ALTER TABLE "ExternalIdentifier" ADD COLUMN "verificationExpiresAt" TIMESTAMP;

ALTER TYPE "AuditLogAction" ADD VALUE IF NOT EXISTS "EXTERNAL_IDENTIFIER_LINKED";
ALTER TYPE "AuditLogAction" ADD VALUE IF NOT EXISTS "EXTERNAL_IDENTIFIER_VERIFICATION_SENT";
ALTER TYPE "AuditLogAction" ADD VALUE IF NOT EXISTS "EXTERNAL_IDENTIFIER_VERIFIED";
