/**
 * AUTO-GENERATED by `facet icons generate` - DO NOT EDIT BY HAND.
 *
 * The exact lucide icon subset this app uses (68 icons
 * resolved against lucide-react v1.31.0), plus the default
 * semantic set. Importing from here instead of the full lucide map keeps
 * the bundle tree-shaken: only these icons ship, which avoids pulling the
 * ~1700-icon map (and the memory/heap cost that comes with it).
 *
 * Regenerate when you add or remove icons:
 *   npx facet icons generate
 */

import type { SVGProps } from "react";
import {
  Activity,
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Bell,
  BookOpen,
  Boxes,
  Briefcase,
  Building,
  Building2,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  CircleCheck,
  CircleQuestionMark,
  Code,
  Compass,
  Copy,
  CreditCard,
  FileCheck,
  FileText,
  FingerprintPattern,
  Globe,
  GraduationCap,
  HeartPulse,
  Key,
  KeyRound,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LayoutPanelLeft,
  List,
  Lock,
  LogOut,
  Mail,
  Menu,
  MessageCircle,
  MessageSquare,
  Monitor,
  Moon,
  Palette,
  PanelLeft,
  Puzzle,
  QrCode,
  Ruler,
  ScanSearch,
  ScrollText,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Sun,
  Terminal,
  Trash,
  TriangleAlert,
  Upload,
  User,
  Users,
  Wallet,
  X,
  Zap,
} from "@arcevo/facet-components/icons";
import type { LucideIcon } from "@arcevo/facet-components/icons";

const ICONS: Record<string, LucideIcon> = {
  "settings": Settings,
  "search": Search,
  "check": Check,
  "x": X,
  "menu": Menu,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevrons-up-down": ChevronsUpDown,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "moon": Moon,
  "sun": Sun,
  "bell": Bell,
  "user": User,
  "users": Users,
  "sparkles": Sparkles,
  "book-open": BookOpen,
  "copy": Copy,
  "trash": Trash,
  "building": Building,
  "list": List,
  "layout-grid": LayoutGrid,
  "file-text": FileText,
  "triangle-alert": TriangleAlert,
  "mail": Mail,
  "message-square": MessageSquare,
  "message-circle": MessageCircle,
  "zap": Zap,
  "palette": Palette,
  "layout-dashboard": LayoutDashboard,
  "circle-question-mark": CircleQuestionMark,
  "credit-card": CreditCard,
  "log-out": LogOut,
  "upload": Upload,
  "qr-code": QrCode,
  "panel-left": PanelLeft,
  "layout-panel-left": LayoutPanelLeft,
  "compass": Compass,
  "layers": Layers,
  "key-round": KeyRound,
  "boxes": Boxes,
  "shield-check": ShieldCheck,
  "terminal": Terminal,
  "puzzle": Puzzle,
  "lock": Lock,
  "ruler": Ruler,
  "fingerprint-pattern": FingerprintPattern,
  "activity": Activity,
  "badge-check": BadgeCheck,
  "briefcase": Briefcase,
  "building-2": Building2,
  "chart-column": ChartColumn,
  "circle-check": CircleCheck,
  "code": Code,
  "file-check": FileCheck,
  "globe": Globe,
  "graduation-cap": GraduationCap,
  "heart-pulse": HeartPulse,
  "key": Key,
  "landmark": Landmark,
  "monitor": Monitor,
  "scan-search": ScanSearch,
  "scroll-text": ScrollText,
  "send": Send,
  "shield": Shield,
  "smartphone": Smartphone,
  "wallet": Wallet,
};

export interface GeneratedIconProps extends SVGProps<SVGSVGElement> {
  name: string;
  className?: string;
  size?: number | string;
}

/** Renders a used icon by name. Unknown names render nothing. */
export function GeneratedIcon({ name, className, size, ...props }: GeneratedIconProps) {
  const kebab = name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
  const Component = ICONS[kebab] ?? ICONS[name];
  if (!Component) return null;
  return <Component className={className} size={size} {...props} />;
}

export default GeneratedIcon;
