"use client";

import GeneratedIcon, { type GeneratedIconProps } from "@/components/ui/icons.generated";

/**
 * ArcID icon component.
 *
 * Delegates to the tree-shaken registry generated by `facet icons generate`
 * (src/components/ui/icons.generated.tsx — exactly the icons this app uses,
 * avoiding the full ~1700-icon lucide map and its memory/heap cost).
 *
 * Keep the registry current after adding/removing icons:
 *   npx facet icons generate
 */
export function Icon(props: GeneratedIconProps) {
  return <GeneratedIcon {...props} />;
}

export type { GeneratedIconProps as IconProps };
export default Icon;
